/* Automatically generated by wasm2c */
#ifndef BLA_H_GENERATED_
#define BLA_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_Date;

typedef struct w2c_bla {
  struct w2c_Date* w2c_Date_instance;
  u64 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_g4;
  u32 w2c_g5;
  u32 w2c_g6;
  u32 w2c_g7;
  u32 w2c_g8;
  u32 w2c_g9;
  u32 w2c_g10;
  u32 w2c_g11;
  u64 w2c_g12;
  u64 w2c_g13;
  u32 w2c_g14;
  u32 w2c_0x5F_rtti_base;
  u32 w2c_g16;
  wasm_rt_memory_t w2c_memory;
} w2c_bla;

void wasm2c_bla_instantiate(w2c_bla*, struct w2c_Date*);
void wasm2c_bla_free(w2c_bla*);
wasm_rt_func_type_t wasm2c_bla_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'Date' 'now' */
f64 w2c_Date_now(struct w2c_Date*);

/* export: 'memory' */
wasm_rt_memory_t* w2c_bla_memory(w2c_bla* instance);

/* export: '__rtti_base' */
u32* w2c_bla_0x5F_rtti_base(w2c_bla* instance);

/* export: '__new' */
u32 w2c_bla_0x5F_new(w2c_bla*, u32, u32);

/* export: '_22' */
u32 w2c_bla_0x5F22(w2c_bla*, u32);

/* export: '_10' */
u32 w2c_bla_0x5F10(w2c_bla*, u32);

/* export: '_21' */
u32 w2c_bla_0x5F21(w2c_bla*, u32);

/* export: '_17' */
u32 w2c_bla_0x5F17(w2c_bla*, u32);

/* export: '_16' */
f64 w2c_bla_0x5F16(w2c_bla*);

/* export: '_8' */
u32 w2c_bla_0x5F8(w2c_bla*, u32);

/* export: '_9' */
f32 w2c_bla_0x5F9(w2c_bla*);

/* export: '_2' */
u32 w2c_bla_0x5F2(w2c_bla*, u32);

/* export: '_4' */
u32 w2c_bla_0x5F4(w2c_bla*, u32);

/* export: '_3' */
void w2c_bla_0x5F3(w2c_bla*, u32);

/* export: '_24' */
u32 w2c_bla_0x5F24(w2c_bla*, u32);

/* export: '__pin' */
u32 w2c_bla_0x5F_pin(w2c_bla*, u32);

/* export: '__unpin' */
void w2c_bla_0x5F_unpin(w2c_bla*, u32);

/* export: '__collect' */
void w2c_bla_0x5F_collect(w2c_bla*);

/* export: '_25' */
void w2c_bla_0x5F25(w2c_bla*, u32, u32, u32, u32, u32);

/* export: '_18' */
void w2c_bla_0x5F18(w2c_bla*, u32, u32, u32, u32);

/* export: '_5' */
void w2c_bla_0x5F5(w2c_bla*, u32, u32, u32, u32, u32, u32);

/* export: '_1' */
void w2c_bla_0x5F1(w2c_bla*, u32, u32, u32, u32, u32, u32);

/* export: '_11' */
void w2c_bla_0x5F11(w2c_bla*, u32, u32, u32, u32, u32, u32, u32);

/* export: '_14' */
void w2c_bla_0x5F14(w2c_bla*, u32, u32, u32, u32);

/* export: '_19' */
void w2c_bla_0x5F19(w2c_bla*, u32, u32, u32, u32);

/* export: '_20' */
void w2c_bla_0x5F20(w2c_bla*, u32, u32, u32, u32, u32, u32, u32);

/* export: '_15' */
void w2c_bla_0x5F15(w2c_bla*, u32, u32, u32, u32, u32);

/* export: '_7' */
void w2c_bla_0x5F7(w2c_bla*, u32, u32, u32, u32, u32, u32, u32);

/* export: '_12' */
void w2c_bla_0x5F12(w2c_bla*, u32, u32, u32, u32, u32, u32);

/* export: '_0' */
void w2c_bla_0x5F0(w2c_bla*, u32, u32, u32, u32);

/* export: '_6' */
void w2c_bla_0x5F6(w2c_bla*, u32, u32, u32);

/* export: '_13' */
void w2c_bla_0x5F13(w2c_bla*, u32, u32, u32, u32, u32);

/* export: '_23' */
void w2c_bla_0x5F23(w2c_bla*, u32, u32, u32, u32, u32, u32);

/* export: '_26' */
void w2c_bla_0x5F26(w2c_bla*, u32, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* BLA_H_GENERATED_ */
